[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install", "cd be_aktipan-main && npm install --include=dev"]

[phases.build]
cmds = ["cd be_aktipan-main && npm run build"]

[start]
cmd = "cd be_aktipan-main && npm run start:prod"
