import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'id' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Comprehensive dictionary for translating Aktipan Indonesian UI strings to English
const translationDictionary: Record<string, string> = {
  // Navigation & General
  'Beranda': 'Home',
  'Direktori Game': 'Game Directory',
  'Activity Packs': 'Activity Packs',
  'AI Generator': 'AI Generator',
  'Koleksi Saya': 'My Collections',
  'Sesi Acara': 'Event Sessions',
  'Talent Marketplace': 'Talent Marketplace',
  'Tutorial Academy': 'Tutorial Academy',
  'Live Arena 🎮': 'Live Arena 🎮',
  'Edit Profile': 'Edit Profile',
  'Keluar (Logout)': 'Logout',
  'Masuk': 'Login',
  'Coba Demo': 'Try Demo',
  'Coba Demo Gratis': 'Try Free Demo',
  'Atau coba demo': 'Or try demo',
  'Masuk sebagai Akun Demo': 'Log in as Demo Account',
  'Navigasi Menu': 'Navigation Menu',
  'Sesi Acara Baru': 'New Event Session',
  'Daftar Baru': 'Register New',
  'Kembali': 'Back',
  'Simpan': 'Save',
  'Simpan Perubahan': 'Save Changes',
  'Hapus': 'Delete',
  'Batal': 'Cancel',
  'Detail': 'Details',
  'Hubungi': 'Contact',
  'Cari': 'Search',
  'Filter': 'Filters',
  'Semua': 'All',
  'Kategori': 'Category',
  'Durasi': 'Duration',
  'Tingkat Energi': 'Energy Level',
  'Peralatan': 'Equipment',
  'Format': 'Format',
  'Langkah': 'Step',
  'Nilai': 'Score',
  'Bagikan': 'Share',
  'Mulai': 'Start',
  'Selesai': 'Finish',
  'Mulai Sesi': 'Start Session',
  'Nama Lengkap': 'Full Name',
  'Nomor Telepon': 'Phone Number',
  'Konfirmasi Password': 'Confirm Password',
  'Ubah Role': 'Change Role',
  'Perbarui Profil': 'Update Profile',

  // Categories
  'Semua Kategori': 'All Categories',
  'Ice Breaking': 'Ice Breaking',
  'Energizer': 'Energizer',
  'Fun Games': 'Fun Games',
  'Team Building': 'Team Building',
  'Komunikasi': 'Communication',
  'Kepemimpinan': 'Leadership',
  'Problem Solving': 'Problem Solving',
  'Sales & Service': 'Sales & Service',
  'Kuis & Polling': 'Quiz & Polling',
  'Refleksi': 'Reflection',
  'Travel & Special': 'Travel & Special',

  // Energies
  'Level Energi': 'Energy Level',
  'Semua Energi': 'All Energies',
  'Calm': 'Calm',
  'Calm (Tenang / Refleksif)': 'Calm (Quiet / Reflective)',
  'Medium': 'Medium',
  'Medium (Interaktif / Fokus)': 'Medium (Interactive / Focused)',
  'High': 'High',
  'High Energy (Fisik / Sangat Ramai)': 'High Energy (Physical / Highly Active)',

  // Formats
  'Format Permainan': 'Game Format',
  'Semua Format': 'All Formats',
  'Offline': 'Offline',
  'Offline / Tatap Muka': 'Offline / Face-to-Face',
  'Online': 'Online',
  'Online / Virtual Gmeet/Zoom': 'Online / Virtual Zoom/Meet',
  'Hybrid': 'Hybrid',

  // Durations
  'Durasi Maksimal': 'Max Duration',
  'Semua Durasi': 'All Durations',
  'Sangat Singkat (1 - 3 Menit)': 'Very Short (1 - 3 Minutes)',
  'Cepat (5 Menit)': 'Quick (5 Minutes)',
  'Standar (10 database)': 'Standard (10 Minutes)',
  'Menengah (15 Menit)': 'Medium (15 Minutes)',
  'Lebih Panjang (>= 30 Menit)': 'Longer (>= 30 Minutes)',

  // Footer & Disclaimer
  'Platform direktori aktivitas interaktif siap pakai yang mengubah peserta pasif menjadi partisipan aktif dan ceria.': 'A ready-to-use interactive activity directory platform that turns passive attendees into active, cheerful participants.',
  'Sangkalan (Disclaimer)': 'Disclaimer',
  'Syarat & Ketentuan': 'Terms & Conditions',
  'Kebijakan Privasi': 'Privacy Policy',
  'Tujuan Acara:': 'Event Purpose:',
  'Seminar': 'Seminar',
  'Travel Games': 'Travel Games',
  'Wedding Games': 'Wedding Games',
  'Dibuat oleh': 'Created by',
  'Semangat Partisipan Aktif & Fun.': 'Active & Fun Participant Spirit.',

  // Hero Section
  'Temukan Aktivitas Interaktif untuk Membuat Peserta Lebih ': 'Find Interactive Activities to Make Participants More ',
  'Aktif dan Fun': 'Active and Fun',
  'Aktipan adalah direktori games, ice breaking, energizer, quiz, challenge, role play, simulasi, dan reflection activity siap pakai untuk berbagai kebutuhan acara Anda.': 'Aktipan is a ready-to-use directory of games, ice breakers, energizers, quizzes, challenges, role plays, simulations, and reflection activities for all your event needs.',
  'Cari Aktivitas': 'Search Activities',
  'Lihat Activity Pack': 'View Activity Pack',
  'Uji Coba AI Democall': 'Try AI Demo Call',
  'TERBARU: AKTIVITAS GENERATOR DENGAN AI': 'NEW: AI-POWERED ACTIVITY GENERATOR',
  'Saran & Cari Aktivitas Langsung dari 132 Database Aktipan': 'Suggestions & Live Activity Search from 132 Aktipan Database',
  'Coba cari atau gunakan filter di bawah ini untuk melihat keajaiban direktori kami.': 'Try searching or use the filters below to see the magic of our directory.',
  'Cari ice breaking 5 menit, games teamwork, energizer tanpa alat, quiz online, role play sales...': 'Search 5-min ice breakers, teamwork games, energizers without tools, online quizzes, sales role play...',
  'Filter Kategori Aktivitas:': 'Filter Activity Category:',
  'Level Energi:': 'Energy Level:',
  'Format Permainan:': 'Game Format:',
  'Durasi Maksimal:': 'Max Duration:',
  'Cari Aktivitas Seru...': 'Search Fun Activities...',

  // AI Generator View
  'Generate Aktivitas Baru Menggunakan Kecerdasan Buatan (AI)': 'Generate New Activity Using Artificial Intelligence (AI)',
  'Sesuaikan dengan audiens, durasi, dan tujuan acara Anda secara instan.': 'Tailor to your audience, duration, and event goals instantly.',
  'Tulis Tema / Topik Sesi': 'Write Session Theme / Topic',
  'Cth: Kepemimpinan, Kreativitas, Ice Breaking setelah makan siang, dsb.': 'E.g., Leadership, Creativity, Ice Breaking after lunch, etc.',
  'Tipe Audiens / Peserta': 'Audience / Participant Type',
  'Cth: Korporat, Mahasiswa, Anak-anak, Tim Developer': 'E.g., Corporate, Students, Kids, Developer Team',
  'Jumlah Peserta': 'Number of Participants',
  'Cth: 10-20 orang, 50+ orang': 'E.g., 10-20 people, 50+ people',
  'Peralatan yang Tersedia': 'Available Equipment',
  'Cth: Tanpa Alat, Kertas & Pena, Smartphone, dsb.': 'E.g., No Tools, Paper & Pen, Smartphone, etc.',
  'Rancang Aktivitas dengan AI': 'Design Activity with AI',
  'Merancang aktivitas dengan AI...': 'Designing activity with AI...',
  'Aktivitas Hasil AI': 'AI Generated Activity',
  'Gunakan Aktivitas Ini': 'Use This Activity',
  'Simpan ke Koleksi': 'Save to Collection',
  'Aktivitas berhasil digenerate!': 'Activity successfully generated!',

  // Marketplace
  'Temukan Talent Fasilitator, MC, & Trainer Terbaik': 'Find the Best Facilitator, MC, & Trainer Talents',
  'Hubungkan acara hebat Anda dengan profesional interaktif berpengalaman untuk hasil maksimal.': 'Connect your great event with experienced interactive professionals for maximum results.',
  'Cari berdasarkan nama, kota, keahlian...': 'Search by name, city, skill...',
  'Kategori Keahlian': 'Skill Category',
  'Fasilitator': 'Facilitator',
  'Master of Ceremony': 'Master of Ceremony',
  'Trainer HR': 'HR Trainer',
  'Host Hiburan': 'Entertainment Host',
  'Hubungi Talent': 'Contact Talent',
  'Detail Profil': 'Profile Details',
  'Lokasi': 'Location',
  'Pengalaman': 'Experience',
  'Tahun': 'Years',
  'Bahasa': 'Languages',
  'Tarif Estimasi': 'Estimated Rate',
  'Hubungi via WhatsApp': 'Contact via WhatsApp',

  // Packs
  'Pilih Bundel Activity Pack untuk Acara Spesifik': 'Choose Activity Pack Bundle for Specific Events',
  'Rangkaian aktivitas yang dirancang runut & terstruktur untuk mensukseskan berbagai tipe event.': 'A sequence of activities designed sequentially & structurally to guarantee event success.',
  'Gunakan Pack Ini': 'Use This Pack',
  'Jumlah Game': 'Number of Games',
  'Total Durasi': 'Total Duration',
  'Rekomendasi Acara': 'Recommended Event',
  'Langkah Urutan Sesi': 'Session Sequence Steps',

  // Sessions
  'Kelola Sesi Acara Anda': 'Manage Your Event Sessions',
  'Buat jadwal alur aktivitas, undang peserta, dan pantau jalannya acara secara interaktif.': 'Create activity schedule flows, invite participants, and monitor event execution interactively.',
  'Buat Sesi Baru': 'Create New Session',
  'Nama Sesi Acara': 'Event Session Name',
  'Cth: Workshop Team Building Mandiri': 'E.g., Independent Team Building Workshop',
  'Tanggal Acara': 'Event Date',
  'Waktu': 'Time',
  'Tambah Aktivitas ke Sesi': 'Add Activity to Session',
  'Belum ada aktivitas di sesi ini': 'No activities in this session yet',
  'Jalankan Sesi Acara': 'Run Event Session',
  'Detail Sesi': 'Session Details',

  // Live Arena
  'Live Arena Interaktif 🎮': 'Interactive Live Arena 🎮',
  'Ubah audiens pasif menjadi aktif dengan ruang interaksi real-time, trivia, dan kuis langsung.': 'Turn passive audience into active with real-time interaction rooms, trivia, and live quizzes.',
  'Buat Arena Baru': 'Create New Arena',
  'Gabung ke Arena': 'Join Arena',
  'Kode PIN Arena': 'Arena PIN Code',
  'Cth: 88291': 'E.g., 88291',
  'Masukkan Nama Anda': 'Enter Your Name',
  'Mulai Room Trivia': 'Start Trivia Room',
  'Peserta yang Bergabung': 'Joined Participants',
  'Pertanyaan Kuis': 'Quiz Questions',
  'Skor Papan Peringkat': 'Leaderboard Scores',

  // Profile
  'Pengaturan Profil & Kredensial': 'Profile Settings & Credentials',
  'Kelola informasi akun, peran default, dan preferensi direktori interaktif Anda.': 'Manage your account info, default roles, and interactive directory preferences.',
  'Simpan Profil': 'Save Profile',
  'Peran Utama': 'Primary Role',
  'Ubah Foto Profil': 'Change Profile Photo',
  'Nama Pengguna': 'Username',
  'Alamat Email': 'Email Address',

  // Collections
  'Koleksi Aktivitas Saya': 'My Activity Collection',
  'Simpan dan kelola aktivitas ice breaking & energizer favorit Anda untuk persiapan acara cepat.': 'Save and manage your favorite ice breaking & energizer activities for quick event prep.',
  'Belum ada aktivitas yang disimpan': 'No saved activities yet',
  'Telusuri Direktori': 'Browse Directory',
  'Hapus dari Koleksi': 'Remove from Collection',

  // Tutorials
  'Tutorial Academy & Tips Fasilitator': 'Tutorial Academy & Facilitator Tips',
  'Pelajari teknik memandu, rahasia ice breaking sukses, dan cara menghadapi audiens yang kaku.': 'Learn facilitation techniques, secrets of successful ice breaking, and how to deal with quiet audiences.',
  'Cari tutorial...': 'Search tutorials...',
  'Kategori Tutorial': 'Tutorial Category',
  'Pemula': 'Beginner',
  'Menengah': 'Intermediate',
  'Profesional': 'Professional',
  'Baca Selengkapnya': 'Read More',

  // Auth Modal Extra
  'Silakan isi form di bawah ini untuk masuk': 'Please fill in the form below to log in',
  'Silakan isi form di bawah ini untuk mendaftar': 'Please fill in the form below to register',
  'Nomor Telepon Anda': 'Your Phone Number',
  'Konfirmasi password Anda': 'Confirm your password',
  'Saya menyetujui Syarat & Ketentuan Aktipan': 'I agree to the Terms & Conditions of Aktipan',
  'Saya menyetujui Kebijakan Privasi data pengguna': 'I agree to the User Data Privacy Policy',
  'Masuk Akun': 'Log In',
  'Daftar Sekarang': 'Register Now',
  'Daftar': 'Register',
  'Belum punya akun?': 'Don\'t have an account?',
  'Sudah memiliki akun?': 'Already have an account?',

  // Directory Dashboard Extra
  'Total Database': 'Total Database',
  'Tersimpan': 'Saved',
  'Kebutuhan Acara': 'Event Needs',
  'Dukungan Lisensi': 'License Support',
  'SaaS SIAP JUAL': 'SaaS READY TO SELL',
  'Aktivitas': 'Activities',
  'Favorit': 'Favorites',
  'Akses Instan Game Generator & Run Mode Terintegrasi': 'Instant Access Game Generator & Integrated Run Mode',
  'Pilih di antara 132 petunjuk taktis MC premium, simpan aktivitas panggung favorit Anda ke folder koleksi, atau sesuaikan panggung secara real-time dengan meluncurkan Run Mode yang bersenjatakantimer interaktif.': 'Choose from 132 premium MC tactical guides, save your favorite stage activities to collection folders, or customize the stage in real-time by launching Run Mode armed with an interactive timer.',
  'Estimasi Fun Level: 4.9/5.0': 'Estimated Fun Level: 4.9/5.0',
  'Simulasi Kapasitas: 1 - 500+ Audiens': 'Capacity Simulation: 1 - 500+ Audience',
  'Direktori Aktivitas Utama': 'Main Activity Directory',
  'Filter multi-dimensi instan untuk meramu aktivitas trainer secara taktis.': 'Instant multi-dimensional filter to tactically prepare trainer activities.',
  'Panduan Tur 💡': 'Tour Guide 💡',
  'Buat Aktivitas Custom': 'Create Custom Activity',
  'Cari kata kunci, nomor aktivitas, atau ketersediaan alat...': 'Search keywords, activity number, or equipment availability...',
  'Terpopuler (Usage Count)': 'Most Popular (Usage Count)',
  'Rating Tertinggi': 'Highest Rating',
  'Durasi Tercepat': 'Fastest Duration',
  'Paling Mudah': 'Easiest',
  'Energi': 'Energy',
  'Kesulitan': 'Difficulty',
  'Kebutuhan Alat': 'Equipment Needs',
  'Semua Kesulitan': 'All Difficulties',
  'Semua Alat': 'All Tools',
  'Hanya Tanpa Alat': 'No Tools Only',
  'Butuh Alat Tambahan': 'Requires Additional Tools',
  'Ditemukan': 'Found',
  'dari total': 'of total',
  'aktivitas interaktif.': 'interactive activities.',
  'Belum ada aktivitas yang cocok': 'No matching activities yet',
  '“Belum ada aktivitas yang cocok. Coba ubah filter pencarian Anda atau gunakan fitur AI Generator.”': '“No matching activities yet. Try changing your search filters or use the AI Generator feature.”',
  'Clear filters': 'Clear filters',
  'Folder Koleksi Anda': 'Your Collection Folders',
  'Belum ada folder koleksi': 'No collection folders yet',
  'Buat folder untuk mengelompokkan aktivitas favorit Anda agar lebih mudah ditemukan saat akan digunakan.': 'Create folders to group your favorite activities so they are easier to find when needed.',
  'Buat koleksi pertama Anda': 'Create your first collection',
  'Aktivitas tersimpan': 'saved activities',
  'Folder masih kosong. Tambahkan dari draf di bawah.': 'Folder is empty. Add some from the draft below.',
  'Semua Aktivitas Tersimpan': 'All Saved Activities',
  'Daftar semua aktivitas yang telah Anda tandai simpan.': 'List of all activities you have saved.',
  'Total': 'Total',
  'Belum ada aktivitas tersimpan': 'No saved activities yet',
  'Eksplorasi direktori kami dan simpan aktivitas favorit Anda agar muncul di sini.': 'Explore our directory and save your favorite activities to see them here.',
  '+ Tambah ke Folder': '+ Add to Folder',
  'Folder koleksi baru berhasil dibuat!': 'New collection folder successfully created!',
  'Koleksi berhasil dihapus.': 'Collection successfully deleted.',
  'Aktivitas berhasil dimasukkan ke dalam folder koleksi!': 'Activity successfully added to collection folder!',
  'Ice Breaking Favorit': 'Favorite Ice Breakers',
  'Kumpulan game cepat di awal sesi pelatihan kantor.': 'Collection of quick games at the beginning of office training sessions.',
  'Games Tanpa Alat': 'Games Without Tools',
  'Daftar aktivitas darurat saat panitia lupa sewa perlengkapan.': 'Emergency activity list when the committee forgets to rent equipment.',
  'Team Building Indoor': 'Indoor Team Building',
  'Merangkul kebersamaan karyawan di dalam ruangan meeting.': 'Embrace employee togetherness inside the meeting room.',
  'Koleksi custom berdaya guna tinggi.': 'High-performance custom collection.',
  'Buat Folder Koleksi Baru': 'Create New Collection Folder',
  'Nama Koleksi': 'Collection Name',
  'e.g. Sesi Pembuka Webinar': 'e.g., Webinar Opening Session',
  'Deskripsi Singkat': 'Short Description',
  'e.g. Daftar game untuk webinar berdurasi singkat': 'e.g., List of games for short-duration webinars',
  'Simpan Koleksi': 'Save Collection',
  'Hapus Koleksi': 'Delete Collection',

  // Rundown sessions
  'Sesi & Rundown Acara': 'Sessions & Event Rundowns',
  'Rancang dan kelompokkan rangkaian aktivitas menjadi satu rundown utuh untuk kemudahan eksekusi acara Anda.': 'Design and group your sequence of activities into a single complete rundown for easy event execution.',
  'Buat Rangkaian Sesi': 'Create Session Sequence',
  'Rancang Sesi Baru': 'Design New Session',
  'Nama Acara Sesi': 'Event Session Name',
  'Tanggal Pelaksanaan': 'Execution Date',
  'Konteks / Tema': 'Context / Theme',
  'Target Audiens': 'Target Audience',
  'Estimasi Peserta': 'Estimated Participants',
  'Simpan Sesi': 'Save Session',
  'Rundown Terjadwal': 'Scheduled Rundowns',
  'Belum ada rundown acara': 'No event rundowns yet',
  'Mulai rancang rundown aktivitas Anda untuk memudahkan pelaksanaan acara.': 'Start designing your activity rundowns for smoother event execution.',
  'Buat rundown pertama': 'Create first rundown',
  'Orang': 'People',
  'Hapus Sesi': 'Delete Session',
  'Rundown Permainan': 'Game Rundown',
  'Belum ada aktivitas di rundown ini.': 'No activities in this rundown yet.',
  'Sesi rundown baru berhasil dibuat!': 'New rundown session successfully created!',
  'Sesi rundown berhasil dihapus.': 'Rundown session successfully deleted.',
  'Rapat Kerja Tahunan 2026': 'Annual Working Meeting 2026',
  'Manager & Staf Divisi HR': 'Manager & Staff of HR Division',
  'Buka dengan ice breaking fakta, pertengahan beri tepuk fokus.': 'Open with fact ice breaking, give focus applause in the middle.',
  'Seminar Motivasi Mahasiswa Baru': 'New Student Motivation Seminar',
  'Mahasiswa Baru angkatan 2026': 'New Students of Class 2026',
  'Fokus refleksi di penutup panggung.': 'Reflective focus at the end of the stage.',
  'Rangkaian rancangan interaktif siap pake.': 'Interactive design sequence ready-to-use.',

  // Detail View Extra
  'Cara Main & Video Tutorial': 'How to Play & Video Tutorial',
  'Baru!': 'New!',
  'Panduan & Debrief': 'Guide & Debrief',
  'Script MC & Tips': 'MC Script & Tips',
  'Variasi & AI Generator': 'Variations & AI Generator',
  'Risiko & Mitigasi': 'Risks & Mitigations',

  // --- Home / PublicWebsite Extra ---
  'Bagaimana Langkah Kerja Aktipan?': 'How does Aktipan work?',
  'Dapatkan workflow run-mode komplit untuk mengaktifkan keriuhan acara secara instan dan cemerlang.': 'Get a complete run-mode workflow to instantly and brilliantly activate event excitement.',
  'Telusuri ribuan data berdasarkan nama/tools.': 'Browse thousands of entries based on name/tools.',
  'Filter Kebutuhan': 'Filter Needs',
  'Dapatkan opsi instan menurut energy & format.': 'Get instant options according to energy & format.',
  'Buka Detail': 'Open Details',
  'Pelajari script MC, do & donts, dan mitigasi.': 'Learn MC scripts, do\'s & don\'ts, and mitigation.',
  'Pelajari Tutorial': 'Study Tutorials',
  'Dapatkan video preview instruksi peserta.': 'Get preview video of participant instructions.',
  'Kelompokkan ke pack custom milik Anda.': 'Group into your own custom pack.',
  'Jalankan Aktivitas': 'Run Activity',
  'Hadirkan timer layar penuh, scoring, & leaderboard.': 'Bring full-screen timer, scoring, & leaderboard.',
  'TESTIMONI PENGGUNA': 'USER TESTIMONIALS',
  'Kata Mereka yang Telah Menggunakan Aktipan': 'What Those Who Have Used Aktipan Say',
  'Dengarkan langsung cerita sukses dari para trainer, MC, guru, HR, dan event organizer yang sukses meningkatkan antusiasme peserta hingga 200%.': 'Listen directly to success stories from trainers, MCs, teachers, HR, and event organizers who successfully increased participant enthusiasm by up to 200%.',
  '"Aktipan benar-benar game changer! Dulu saya butuh waktu berjam-jam untuk meriset ice breaking yang cocok untuk corporate workshop. Sekarang tinggal filter berdasarkan energi, durasi, dan format, semuanya langsung tersedia dalam hitungan detik."': '"Aktipan is a real game changer! I used to spend hours researching suitable ice breakers for corporate workshops. Now I just filter by energy, duration, and format, and everything is instantly available in seconds."',
  'Andri Wijaya': 'Andri Wijaya',
  'Senior Corporate Trainer': 'Senior Corporate Trainer',
  '"Menghadapi murid-murid generasi Z yang gampang bosan adalah tantangan besar. Berkat Aktipan, saya selalu punya ide game interaktif seru setiap memulai kelas. Murid-murid jadi jauh lebih antusias and fokus belajar meningkat drastis!"': '"Facing Gen Z students who get bored easily is a big challenge. Thanks to Aktipan, I always have fun interactive game ideas every time I start class. Students are much more enthusiastic and focus has improved dramatically!"',
  'Siti Rahmawati': 'Siti Rahmawati',
  'Guru SMA': 'High School Teacher',
  '"Sebagai MC acara besar, saya dituntut untuk selalu bisa mencairkan suasana di awal panggung (opening ice breaking). Direktori Aktipan memberikan saya ratusan variasi taktis petunjuk MC siap pakai yang interaktif. Penonton langsung heboh!"': '"As an MC for large events, I\'m required to always break the ice at the start of the stage (opening ice breaking). The Aktipan directory gives me hundreds of tactical variations of ready-to-use interactive MC guides. The audience goes wild!"',
  'Christian Hartono': 'Christian Hartono',
  'Professional Wedding MC': 'Professional Wedding MC',
  '"Kami memakai Aktipan untuk acara bulanan Team Building internal perusahaan. Sangat menghemat anggaran EO eksternal karena tim HR mandiri pun bisa mengeksekusi aktivitas seru dengan panduan de-brief yang berbobot."': '"We use Aktipan for our company\'s internal monthly Team Building events. It really saves on external EO budget because our in-house HR team can execute fun activities with solid de-brief guides."',
  'Jessica Amalia': 'Jessica Amalia',
  'HR People Development': 'HR People Development',
  'Paket Langganan': 'Subscription Packages',
  'Akses Fleksibel untuk Segala Kebutuhan': 'Flexible Access for All Needs',
  'Mulai dengan gratis lalu upgrade sewaktu-waktu untuk melengkapi toolsets event organizer Anda.': 'Start for free and upgrade anytime to complete your event organizer toolsets.',
  'Plan Free': 'Free Plan',
  'Uji coba akses direktori dasar.': 'Trial access to the basic directory.',
  'Akses 30 Aktivitas Gratis': 'Access to 30 Free Activities',
  'Fitur Pencarian Dasar': 'Basic Search Feature',
  'Simpan 5 Aktivitas': 'Save 5 Activities',
  'Gunakan Versi Free': 'Use Free Version',
  'Plan Starter': 'Starter Plan',
  'Sangat ramah bagi MC pemula kelas privat.': 'Very friendly for beginner MCs of private classes.',
  'Akses 80+ Aktivitas': 'Access to 80+ Activities',
  'Unlimited Saved List': 'Unlimited Saved List',
  'Ekspor PDF Rundown': 'Export PDF Rundowns',
  'Upgrade Starter': 'Upgrade Starter',
  'POPULER • PENUH FITUR': 'POPULAR • FULL FEATURED',
  'Plan Pro': 'Pro Plan',
  'Untuk guru, trainer, korporat profesional.': 'For teachers, trainers, professional corporate speakers.',
  'Semua 132 Aktivitas Premium': 'All 132 Premium Activities',
  'AI Generator Tanpa Batas': 'Unlimited AI Generator',
  'Mode Run & Timer Besar Layar': 'Run Mode & Screen-Sized Timer',
  'Scoring & Leaderboard Real-time': 'Real-time Scoring & Leaderboards',
  'Mulai Langganan Pro': 'Start Pro Subscription',
  'Plan Business': 'Business Plan',
  'Untuk Tim EO / Divisi HR Perusahaan.': 'For EO Teams / Corporate HR Divisions.',
  'Integrasi Multi-Workspace': 'Multi-Workspace Integration',
  'Custom Activity Editor Tim': 'Team Custom Activity Editor',
  'Laporan Analitik Keaktifan': 'Activity Analytics Reports',
  'Hubungi Penjualan': 'Contact Sales',
  'Mulai cari aktivitas yang cocok untuk acara Anda': 'Start finding activities that fit your event',
  'Bergabunglah bersama ribuan panitia yang menghentikan kecanggungan audiens menggunakan Aktipan.': 'Join thousands of organizers who end audience awkwardness using Aktipan.',

  // --- Activity Packs Extra ---
  'Ice Breaking Pack': 'Ice Breaking Pack',
  'Energizer Pack': 'Energizer Pack',
  'Team Building Pack': 'Team Building Pack',
  'Communication Games Pack': 'Communication Games Pack',
  'Leadership Games Pack': 'Leadership Games Pack',
  'Koleksi 10 aktivitas pemecah kebekuan suasana tercepat.': 'Collection of the 10 fastest ice breaking activities.',
  'Koleksi 10 aktivitas pengusir kantuk dan penambah fokus.': 'Collection of 10 sleep-busting and focus-enhancing activities.',
  'Koleksi lengkap aktivitas mengasah sinergi dan trust tim.': 'Complete collection of activities to sharpen team synergy and trust.',
  'Asah kejelasan instruksi verbal dan non-verbal tim.': 'Sharpen the clarity of team verbal and non-verbal instructions.',
  'Melatih delegasi krisis, pengambilan keputusan taktis.': 'Train crisis delegation, tactical decision making.',
  'Katalog Premium': 'Premium Catalog',
  'Activity Packs Siap Saji': 'Ready-to-use Activity Packs',
  'Dapatkan bundel aktivitas bertema untuk mensukseskan jenis rundown Anda tanpa repot memikirkan instrumen pendukung.': 'Get themed activity bundles to guarantee your rundown success without worrying about supporting tools.',
  'Terbuka': 'Unlocked',
  'Terkunci': 'Locked',
  'Siap Pake': 'Ready to Use',
  'Pembayaran Berhasil! 💸': 'Payment Successful! 💸',
  'Sambut kegembiraan baru! Paket aktivitas premium': 'Welcome a new joy! Premium activity pack',
  'kini telah sukses dibuka dan siap dipakai di workspace Anda.': 'has been successfully unlocked and is ready to use in your workspace.',
  'Workspace Teraktualisasi Otomatis': 'Workspace Automatically Updated',
  'Mulai Gunakan Sekarang ✓': 'Start Using Now ✓',
  'Akses': 'Access',
  'Aktivitas Premium': 'Premium Activities',

  // --- Game Directory Extra ---
  'Aksi': 'Actions',
  'Deskripsi & Tujuan': 'Description & Purpose',
  'Estimasi Sesi': 'Session Estimate',
  'Atribut': 'Attributes',
  'Kategori Utama': 'Primary Category',
  'Tujuan / Goal': 'Purpose / Goal',
  'Deskripsi Singkat Cara Main': 'Short Gameplay Description',
  'Tambah Baru': 'Add New',
  'Tambah Aktivitas Custom Anda': 'Add Your Custom Activity',
  'Nama Aktivitas': 'Activity Name',
  'Durasi Maksimal (Menit)': 'Max Duration (Minutes)',

  // --- Talent Marketplace Extra ---
  'Dukungan Ekosistem': 'Ecosystem Support',
  'Talent & Vendor Marketplace': 'Talent & Vendor Marketplace',
  'Sewa jasa fasilitator game tersertifikasi, MC pernikahan heboh, atau sewa peralatan panggung event raksasa langsung dari vendor terpercaya.': 'Hire certified game facilitators, lively wedding MCs, or giant stage equipment rentals directly from trusted vendors.',
  '📍 Lokasi: ': '📍 Location: ',
  'Spesialis Layanan:': 'Service Specialties:',
  'Tarif Partner': 'Partner Rate',
  'Tanya / Hubungi': 'Ask / Contact',
  'Booking Terkirim! 📅': 'Booking Sent! 📅',
  'Pengajuan konsultasi dan booking untuk talent partner': 'Consultation and booking request for talent partner',
  'telah berhasil dilayangkan.': 'has been successfully submitted.',
  'Langkah Selanjutnya:': 'Next Steps:',
  '1. Tim': '1. Team',
  'akan memproses ketersediaan jadwal.': 'will process schedule availability.',
  '2. Anda akan dihubungi oleh admin resmi via WhatsApp/Email dalam tempo maksimal': '2. You will be contacted by the official admin via WhatsApp/Email within a maximum of',
  '2 jam kerja': '2 working hours',
  'Selesai ✓': 'Done ✓',
  'Trainer Professional': 'Professional Trainer',
  'Fasilitator Outbound': 'Outbound Facilitator',
  'Vendor Alat Games': 'Game Equipment Vendor',
  'Katalog Sewa Heboh': 'Exciting Rental Catalog',
  'Sewa Papan Puzzle Raksasa': 'Giant Puzzle Board Rental',
  'Import Tarik Tambang Profesional': 'Professional Tug of War Import',
  'High Rope Iceberg': 'High Rope Iceberg',
  'Character Building': 'Character Building',
  'Wedding Games Specialist': 'Wedding Games Specialist',
  'Family Gathering Host': 'Family Gathering Host',
  'Corporate Teamwork': 'Corporate Teamwork',
  'Leadership Outbound': 'Leadership Outbound',
  'Jakarta, Indonesia': 'Jakarta, Indonesia',
  'Bandung, Indonesia': 'Bandung, Indonesia',
  'Bogor, Indonesia': 'Bogor, Indonesia',
  'Surabaya, Indonesia': 'Surabaya, Indonesia',

  // --- Tutorial Academy Extra ---
  'AKTIPAN INSTRUCTOR COCKPIT': 'AKTIPAN INSTRUCTOR COCKPIT',
  'Academy & Video Tutorial Center': 'Academy & Video Tutorial Center',
  'Kuasai panggung, asah suara pembawa acara (vocal presence), dan ketahui taktik jeli merancang skenario ice breaking kustom demi melipatgandakan kepuasan klien korporat.': 'Master the stage, sharpen your voice presence, and discover clever tactics for designing custom ice-breaking scenarios to multiply corporate client satisfaction.',
  'Sertifikasi Premium': 'Premium Certification',
  '7 Modul Kursus Aktif': '7 Active Course Modules',
  'Sukses Dipelajari': 'Successfully Studied',
  'Instruktur': 'Instructor',
  'Senior Trainer & MC Partner': 'Senior Trainer & MC Partner',
  '5.0 (482 ulasan)': '5.0 (482 reviews)',
  'Pencarian Tutorial': 'Tutorial Search',
  'Cari berdasarkan judul tutorial, kategori, level...': 'Search by tutorial title, category, level...',
  'Tingkat Kesulitan Kursus': 'Course Difficulty Level',
  'Semua Level': 'All Levels',
  'Pemula (Beginner)': 'Beginner',
  'Menengah (Intermediate)': 'Intermediate',
  'Profesional (Expert)': 'Expert',
  'Kemajuan Belajar Anda': 'Your Learning Progress',
  'Selesai Membaca & Menonton': 'Finished Reading & Watching',
  'Beri Tanda Selesai': 'Mark as Completed',
  'Sertifikat Kelulusan': 'Certificate of Completion',
  'Hebat! Anda telah menyelesaikan seluruh kursus.': 'Great! You have completed all courses.',
  'Klaim Sertifikat': 'Claim Certificate',
  'Simulasi Video Player': 'Simulated Video Player',
  'Instruksi Video Utama': 'Main Video Instructions',
  'Catatan Pendukung': 'Supporting Notes',
  'Teknik & Script MC Praktis': 'Practical MC Script & Techniques',
  'Poin Kunci Sesi': 'Key Session Points',
  'Langkah Berikutnya': 'Next Step',
  'Buka Materi Berikutnya': 'Open Next Lesson',
  'Tambahkan Catatan Baru': 'Add New Note',
  'Catatan berhasil ditambahkan!': 'Note successfully added!',

  // --- Live Arena Extra ---
  'Live Arena & Real-time Interaction': 'Live Arena & Real-time Interaction',
  'Daftar Room Aktif': 'Active Room List',
  'Daftar Aktivitas Gabung': 'Join Activity List',
  'Kode PIN': 'PIN Code',
  'Gabung Sesi': 'Join Session',
  'Kuis Trivia Real-time': 'Real-time Trivia Quiz',
  'Bertanding': 'Competing',
  'Bersiap': 'Preparing',
  'Baru saja': 'Just now',
  '1m lalu': '1m ago',
  '2m lalu': '2m ago',
  '3m lalu': '3m ago',
  'Komentar Komunitas': 'Community Comments',
  'Tulis pesan Anda...': 'Write your message...',
  'Kirim': 'Send',

  // --- Auth Modal Extra ---
  'AKTIPAN WORKSPACE': 'AKTIPAN WORKSPACE',
  'SaaS Premium Active & Fun Games': 'SaaS Premium Active & Fun Games',
  'Email': 'Email',
  'Password': 'Password',
  'Pilih Peran Utama Anda': 'Choose Your Primary Role',
  'Pelatih & Pembicara': 'Trainer & Speaker',
  'Pemandu Acara': 'Event Guide / MC',
  'Pemandu Kelompok': 'Group Facilitator',
  'HR / L&D': 'HR / L&D',
  'Corporate HRD': 'Corporate HRD',
  'Guru / Dosen': 'Teacher / Lecturer',
  'Pendidik Akademik': 'Academic Educator',
  'EO': 'Event Organizer',
  'Penyelenggara Acara': 'Event Organizer',

  // --- Edit Profile Extra ---
  'Informasi Akun': 'Account Information',
  'Keahlian': 'Skills',
  'Sertifikasi': 'Certifications',
  'Riwayat Main': 'Gameplay History',
  'Rekomendasi Preferensi': 'Recommendation Preferences',
  'Profil berhasil diperbarui!': 'Profile updated successfully!',
  'Password berhasil diperbarui!': 'Password updated successfully!',
  'Ubah Foto': 'Change Photo',
  'Ubah Password': 'Change Password',
  'Password Lama': 'Old Password',
  'Password Baru': 'New Password',
  'Ubah Password Sekarang': 'Change Password Now',
  'Keahlian & Kompetensi Fasilitator': 'Facilitator Skills & Competencies',
  'Tambah Keahlian': 'Add Skill',
  'Sertifikasi Profesional': 'Professional Certifications',
  'Tambah Sertifikasi': 'Add Certification',
  'Riwayat Sesi Game': 'Game Session History',
  'Tambah Riwayat Sesi': 'Add Session History',
  'Preferensi Rekomendasi': 'Recommendation Preferences',
  'Dapatkan Rekomendasi Aktivitas': 'Get Activity Recommendations',
};

// Word-by-word replacer fallback for dynamic text templates
const wordReplacements: Record<string, string> = {
  'Kembali': 'Back',
  'Simpan': 'Save',
  'Hapus': 'Delete',
  'Kategori': 'Category',
  'Peralatan': 'Equipment',
  'Durasi': 'Duration',
  'Format': 'Format',
  'Calm': 'Calm',
  'Medium': 'Medium',
  'High': 'High',
  'Offline': 'Offline',
  'Online': 'Online',
  'Hybrid': 'Hybrid',
  'menit': 'minutes',
  'Menit': 'Minutes',
  'Tanpa Alat': 'No Tools',
  'Orang': 'People',
  'orang': 'people',
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    return (localStorage.getItem('aktipan_language') as Language) || 'id';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('aktipan_language', lang);
  };

  const t = (key: string): string => {
    if (language === 'id') return key;
    
    // 1. Check direct exact match in dictionary
    if (translationDictionary[key]) {
      return translationDictionary[key];
    }

    // 2. Partial template matches for common dynamic strings
    let translated = key;
    for (const [ind, eng] of Object.entries(wordReplacements)) {
      const regex = new RegExp(`\\b${ind}\\b`, 'gi');
      translated = translated.replace(regex, eng);
    }
    
    return translated;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
